name: Daily Scrap Trigger

on:
  schedule:
    - cron: "30 4 * * *"
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: HTTP Request Action
      id: myRequest
      uses: fjogeleit/http-request-action@v1.16.4
      with:
        url: ${{ secrets.API_URL }}
        method: 'GET'
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ steps.myRequest.outputs.status }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}

