name: Daily API Call

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Log time
        run: |
          echo "Hello World!"
