name: Demo Echo

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Log time
        run: |
          echo "Hello World!"
